/* eslint-disable */
/**
 * ARCHIVO GENERADO — NO EDITAR A MANO.
 *
 * Lo produce `scripts/codegen-api-client.sh` a partir del esquema OpenAPI de
 * la API de Vendi (`./openapi.json`, en este mismo directorio). Cualquier
 * edición manual se pierde en la siguiente regeneración, y el CI la detecta
 * con `codegen + git diff --exit-code`.
 */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/platform/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar negocios */
        get: operations["listar_tenants_api_v1_platform_tenants_get"];
        put?: never;
        /**
         * Dar de alta un negocio
         * @description Crea el negocio y su Organization en Keycloak, en ese orden y con compensación.
         *
         *     Si Keycloak falla, no queda fila: se deshace la transacción y sube un error
         *     tipado (502 con sobre estándar), no un 500 con traza.
         *
         *     Dos negocios pueden llamarse igual: el nombre no es identidad. Ver la nota
         *     de `create_organization` sobre por qué el `name` de la Organization es el
         *     UUID y no el nombre comercial.
         */
        post: operations["crear_tenant_api_v1_platform_tenants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/tenants/{tenant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ver un negocio */
        get: operations["ver_tenant_api_v1_platform_tenants__tenant_id__get"];
        put?: never;
        post?: never;
        /**
         * Dar de baja un negocio
         * @description Borrado lógico de la fila + borrado de la Organization en Keycloak.
         *
         *     La fila sobrevive para la auditoría y para que su `id` —que fue alias de una
         *     Organization— no se reutilice jamás.
         */
        delete: operations["eliminar_tenant_api_v1_platform_tenants__tenant_id__delete"];
        options?: never;
        head?: never;
        /**
         * Renombrar o suspender un negocio
         * @description Cambia nombre y/o estado. Suspender aquí corta el acceso en ≤ TTL del cache.
         *
         *     `estado="eliminado"` se rechaza a propósito: la baja tiene efectos en
         *     Keycloak y tiene su propio verbo (`DELETE`).
         */
        patch: operations["actualizar_tenant_api_v1_platform_tenants__tenant_id__patch"];
        trace?: never;
    };
    "/api/v1/productos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar productos */
        get: operations["listar_productos_api_v1_productos_get"];
        put?: never;
        /**
         * Crear un producto
         * @description Acepta el `id` que traiga el cliente (ADR-017): reenviar la misma
         *     creación devuelve el producto ya creado, sin duplicar fila ni evento.
         */
        post: operations["crear_producto_api_v1_productos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/productos/por-codigo/{codigo}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar un producto por código de barras
         * @description El camino del escáner (ADR-024): un EAN resuelve a exactamente un
         *     producto, gracias al índice único parcial.
         */
        get: operations["buscar_por_codigo_api_v1_productos_por_codigo__codigo__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/productos/{producto_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ver un producto */
        get: operations["ver_producto_api_v1_productos__producto_id__get"];
        put?: never;
        post?: never;
        /**
         * Dar de baja un producto (borrado lógico)
         * @description Marca `deleted_at` y libera el EAN. La fila sobrevive: el historial de
         *     ventas la referencia (ADR-019).
         */
        delete: operations["eliminar_producto_api_v1_productos__producto_id__delete"];
        options?: never;
        head?: never;
        /**
         * Actualizar un producto
         * @description No acepta `stock_actual` ni `ultimo_costo`: el stock lo mueven los
         *     movimientos de inventario y el costo las compras (ADR-020).
         */
        patch: operations["actualizar_producto_api_v1_productos__producto_id__patch"];
        trace?: never;
    };
    "/api/v1/tenants/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** El negocio de la sesión actual */
        get: operations["mi_negocio_api_v1_tenants_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sonda de vida
         * @description Responde sin tocar ninguna dependencia externa.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sonda de vida (alias) */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sonda de disponibilidad */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Métricas Prometheus (requiere credencial propia) */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ErrorResponse */
        ErrorResponse: {
            /**
             * Code
             * @default ERROR
             */
            code: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            } | null;
            /** Message */
            message: string;
            /**
             * Success
             * @default false
             */
            success: boolean;
        };
        /**
         * EstadoTenant
         * @description Estados de un negocio. Sin tildes ni eñes: viajan en JSON y en URLs.
         * @enum {string}
         */
        EstadoTenant: "activo" | "suspendido" | "eliminado";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PagedList[ProductoSalida] */
        PagedList_ProductoSalida_: {
            /** Items */
            items: components["schemas"]["ProductoSalida"][];
            /** Limit */
            limit: number;
            /** Skip */
            skip: number;
            /** Total */
            total: number;
        };
        /** PagedList[TenantSalida] */
        PagedList_TenantSalida_: {
            /** Items */
            items: components["schemas"]["TenantSalida"][];
            /** Limit */
            limit: number;
            /** Skip */
            skip: number;
            /** Total */
            total: number;
        };
        /**
         * ProductoActualizar
         * @description Todo opcional: es un PATCH. `None` significa "no lo toques" (misma
         *     convención que `TenantActualizar`).
         *
         *     No lleva `stock_actual` ni `ultimo_costo`: el stock lo mueven los
         *     movimientos de inventario y el costo las compras (ADR-020). Un endpoint
         *     que dejara editar el contador a mano rompería la invariante del libro.
         */
        ProductoActualizar: {
            /** Categoria */
            categoria?: string | null;
            /** Codigo Barras */
            codigo_barras?: string | null;
            /** Iva Pct */
            iva_pct?: number | string | null;
            /** Nombre */
            nombre?: string | null;
            /** Padre Id */
            padre_id?: string | null;
            /** Precio Venta */
            precio_venta?: number | null;
            /** Stock Minimo */
            stock_minimo?: number | string | null;
            /** Unidad Medida */
            unidad_medida?: string | null;
        };
        /** ProductoCrear */
        ProductoCrear: {
            /** Categoria */
            categoria?: string | null;
            /** Codigo Barras */
            codigo_barras?: string | null;
            /** Id */
            id?: string | null;
            /**
             * Iva Pct
             * @default 0
             */
            iva_pct: number | string;
            /** Nombre */
            nombre: string;
            /** Padre Id */
            padre_id?: string | null;
            /** Precio Venta */
            precio_venta: number;
            /**
             * Stock Minimo
             * @default 0
             */
            stock_minimo: number | string;
            /**
             * Unidad Medida
             * @default unidad
             */
            unidad_medida: string;
        };
        /** ProductoSalida */
        ProductoSalida: {
            /** Categoria */
            categoria?: string | null;
            /** Codigo Barras */
            codigo_barras?: string | null;
            /** Created At */
            created_at?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Iva Pct */
            iva_pct: string;
            /** Nombre */
            nombre: string;
            /** Padre Id */
            padre_id?: string | null;
            /** Precio Venta */
            precio_venta: number;
            /** Stock Actual */
            stock_actual: string;
            /** Stock Minimo */
            stock_minimo: string;
            /** Ultimo Costo */
            ultimo_costo: number;
            /** Unidad Medida */
            unidad_medida: string;
        };
        /**
         * TenantActualizar
         * @description Todo opcional: es un PATCH. `None` significa "no lo toques".
         */
        TenantActualizar: {
            estado?: components["schemas"]["EstadoTenant"] | null;
            /** Nombre */
            nombre?: string | null;
        };
        /** TenantCrear */
        TenantCrear: {
            /** Nombre */
            nombre: string;
        };
        /** TenantSalida */
        TenantSalida: {
            /** Created At */
            created_at?: string | null;
            estado: components["schemas"]["EstadoTenant"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kc Org Id */
            kc_org_id?: string | null;
            /** Nombre */
            nombre: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listar_tenants_api_v1_platform_tenants_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
                incluir_eliminados?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedList_TenantSalida_"];
                };
            };
            /** @description Falta el token o no es válido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description El token no trae el permiso platform:admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_tenant_api_v1_platform_tenants_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantCrear"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantSalida"];
                };
            };
            /** @description Falta el token o no es válido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description El token no trae el permiso platform:admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Keycloak no pudo crear la organización */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ver_tenant_api_v1_platform_tenants__tenant_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantSalida"];
                };
            };
            /** @description Falta el token o no es válido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description El token no trae el permiso platform:admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No existe */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    eliminar_tenant_api_v1_platform_tenants__tenant_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Falta el token o no es válido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description El token no trae el permiso platform:admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No existe */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    actualizar_tenant_api_v1_platform_tenants__tenant_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantActualizar"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantSalida"];
                };
            };
            /** @description Falta el token o no es válido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description El token no trae el permiso platform:admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No existe */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_productos_api_v1_productos_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
                /** @description Texto a buscar en el nombre */
                q?: string | null;
                categoria?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedList_ProductoSalida_"];
                };
            };
            /** @description Falta el token o no es válido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Falta el permiso o el negocio está suspendido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_producto_api_v1_productos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductoCrear"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductoSalida"];
                };
            };
            /** @description Falta el token o no es válido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Falta el permiso o el negocio está suspendido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description El producto no existe */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description EAN duplicado o id ya usado */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    buscar_por_codigo_api_v1_productos_por_codigo__codigo__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                codigo: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductoSalida"];
                };
            };
            /** @description Falta el token o no es válido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Falta el permiso o el negocio está suspendido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description El producto no existe */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ver_producto_api_v1_productos__producto_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                producto_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductoSalida"];
                };
            };
            /** @description Falta el token o no es válido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Falta el permiso o el negocio está suspendido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description El producto no existe */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    eliminar_producto_api_v1_productos__producto_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                producto_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Falta el token o no es válido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Falta el permiso o el negocio está suspendido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description El producto no existe */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    actualizar_producto_api_v1_productos__producto_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                producto_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductoActualizar"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductoSalida"];
                };
            };
            /** @description Falta el token o no es válido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Falta el permiso o el negocio está suspendido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description El producto no existe */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description EAN duplicado */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mi_negocio_api_v1_tenants_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantSalida"];
                };
            };
            /** @description El negocio está suspendido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description El negocio ya no existe */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
