/* eslint-disable */
/**
 * ARCHIVO GENERADO — NO EDITAR A MANO.
 *
 * Lo produce `scripts/codegen-api-client.sh` a partir del esquema OpenAPI de
 * la API de Vendi (`./openapi.json`, en este mismo directorio). Cualquier
 * edición manual se pierde en la siguiente regeneración, y el CI la detecta
 * con `codegen + git diff --exit-code`.
 */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Sonda de vida: responde sin tocar ninguna dependencia externa.
         *
         *     Es deliberadamente tonta. Que responda solo prueba que el proceso está
         *     vivo y sirviendo HTTP; la sonda con dependencias es `/health/ready` y
         *     llega en la Etapa 4.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
