/* eslint-disable */
/**
 * ARCHIVO GENERADO — NO EDITAR A MANO.
 *
 * Lo produce `scripts/codegen-api-client.sh` a partir del esquema OpenAPI de
 * la API de Vendi (`./openapi.json`, en este mismo directorio). Cualquier
 * edición manual se pierde en la siguiente regeneración, y el CI la detecta
 * con `codegen + git diff --exit-code`.
 */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/compras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar compras */
        get: operations["listar_compras_api_v1_compras_get"];
        put?: never;
        /**
         * Registrar una compra a proveedor
         * @description En la MISMA transacción: la compra, sus ítems, un movimiento `compra`
         *     por línea, `stock_actual` y `ultimo_costo` de cada producto, y el evento
         *     `compra.registrada` (ADR-020). Acepta el `id` que traiga el cliente
         *     (ADR-017): reenviar la misma compra devuelve la existente, sin duplicar
         *     fila, stock ni evento. El total lo calcula el servidor por línea; el
         *     `proveedor_nombre` es texto libre (la factura es un papel: no hay tabla
         *     de proveedores).
         */
        post: operations["registrar_compra_api_v1_compras_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compras/{compra_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ver una compra con sus ítems */
        get: operations["ver_compra_api_v1_compras__compra_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dispositivos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar un dispositivo del negocio
         * @description Acepta el `id` que traiga el cliente (ADR-017): re-registrar con el
         *     mismo id devuelve el existente, sin duplicar fila.
         */
        post: operations["registrar_dispositivo_api_v1_dispositivos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventario/ajustes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar ajustes y mermas
         * @description La auditoría del «¿quién movió el arroz?»: cada fila lleva su motivo
         *     y quién la aplicó.
         */
        get: operations["listar_ajustes_api_v1_inventario_ajustes_get"];
        put?: never;
        /**
         * Registrar un ajuste por conteo o una merma (ONLINE)
         * @description La única operación de inventario que EXIGE conexión (ADR-020): el
         *     delta se calcula contra el stock del servidor en el momento del conteo —
         *     un ajuste offline corrompería el contador de forma no conmutativa. El
         *     `motivo` es obligatorio. El `id` del cliente es requerido y ancla la
         *     idempotencia: el reintento idéntico devuelve lo ya respondido sin mover
         *     stock; el divergente es 409 `ajuste_id_divergente`. Un conteo que cuadra
         *     (delta 0) graba la fila pero no escribe movimiento en el libro.
         */
        post: operations["registrar_ajuste_api_v1_inventario_ajustes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventario/stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Estado de stock con su nivel (agotado/crítico/bajo/ok)
         * @description El nivel lo deriva el servidor con la misma función que dispara
         *     `inventario.alerta_stock`: una sola definición del umbral. El stock
         *     negativo es un dato legítimo (ADR-020) y viaja como `agotado`.
         */
        get: operations["estado_de_stock_api_v1_inventario_stock_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar negocios */
        get: operations["listar_tenants_api_v1_platform_tenants_get"];
        put?: never;
        /**
         * Dar de alta un negocio
         * @description Crea el negocio y su Organization en Keycloak, en ese orden y con compensación.
         *
         *     Si Keycloak falla, no queda fila: se deshace la transacción y sube un error
         *     tipado (502 con sobre estándar), no un 500 con traza.
         *
         *     Dos negocios pueden llamarse igual: el nombre no es identidad. Ver la nota
         *     de `create_organization` sobre por qué el `name` de la Organization es el
         *     UUID y no el nombre comercial.
         */
        post: operations["crear_tenant_api_v1_platform_tenants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/tenants/{tenant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ver un negocio */
        get: operations["ver_tenant_api_v1_platform_tenants__tenant_id__get"];
        put?: never;
        post?: never;
        /**
         * Dar de baja un negocio
         * @description Borrado lógico de la fila + borrado de la Organization en Keycloak.
         *
         *     La fila sobrevive para la auditoría y para que su `id` —que fue alias de una
         *     Organization— no se reutilice jamás.
         */
        delete: operations["eliminar_tenant_api_v1_platform_tenants__tenant_id__delete"];
        options?: never;
        head?: never;
        /**
         * Renombrar o suspender un negocio
         * @description Cambia nombre y/o estado. Suspender aquí corta el acceso en ≤ TTL del cache.
         *
         *     `estado="eliminado"` se rechaza a propósito: la baja tiene efectos en
         *     Keycloak y tiene su propio verbo (`DELETE`).
         */
        patch: operations["actualizar_tenant_api_v1_platform_tenants__tenant_id__patch"];
        trace?: never;
    };
    "/api/v1/productos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar productos */
        get: operations["listar_productos_api_v1_productos_get"];
        put?: never;
        /**
         * Crear un producto
         * @description Acepta el `id` que traiga el cliente (ADR-017): reenviar la misma
         *     creación devuelve el producto ya creado, sin duplicar fila ni evento.
         */
        post: operations["crear_producto_api_v1_productos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/productos/por-codigo/{codigo}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar un producto por código de barras
         * @description El camino del escáner (ADR-024): un EAN resuelve a exactamente un
         *     producto, gracias al índice único parcial.
         */
        get: operations["buscar_por_codigo_api_v1_productos_por_codigo__codigo__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/productos/{producto_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ver un producto */
        get: operations["ver_producto_api_v1_productos__producto_id__get"];
        put?: never;
        post?: never;
        /**
         * Dar de baja un producto (borrado lógico)
         * @description Marca `deleted_at` y libera el EAN. La fila sobrevive: el historial de
         *     ventas la referencia (ADR-019).
         */
        delete: operations["eliminar_producto_api_v1_productos__producto_id__delete"];
        options?: never;
        head?: never;
        /**
         * Actualizar un producto
         * @description No acepta `stock_actual` ni `ultimo_costo`: el stock lo mueven los
         *     movimientos de inventario y el costo las compras (ADR-020).
         */
        patch: operations["actualizar_producto_api_v1_productos__producto_id__patch"];
        trace?: never;
    };
    "/api/v1/sync/delta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Descargar los cambios del catálogo desde un watermark
         * @description El drenado hacia los dispositivos (ADR-017): productos modificados
         *     desde `desde` y tumbas de los dados de baja. El próximo watermark es el
         *     `hasta` de la respuesta — lo pone el reloj del servidor, nunca el del
         *     cliente.
         *
         *     Los productos del delta son `ProductoSalida` y cumplen la regla del
         *     dato: `ultimo_costo` viaja solo para quien tiene `compra:crear`. El
         *     cajero sincroniza el catálogo al IndexedDB del POS con el costo en null
         *     — el campo SIGUE presente en el contrato, como en los endpoints del
         *     catálogo.
         */
        get: operations["delta_de_sync_api_v1_sync_delta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/lotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aplicar un lote de operaciones de la cola del dispositivo
         * @description Una transacción por lote, un resultado por operación
         *     (`aceptada`/`duplicada`/`rechazada`), en el orden del lote.
         *
         *     HTTP 200 aunque haya operaciones rechazadas: el lote SE PROCESÓ; el
         *     desenlace de cada operación viaja en su resultado. Los 4xx de este
         *     endpoint significan «el request entero es inválido», no «una operación
         *     falló».
         *
         *     Idempotencia y divergencia (decisión 4 del plan): reenviar una operación
         *     con el mismo `id` y un payload IDÉNTICO responde `duplicada` (no-op, sin
         *     evento); el mismo `id` con cualquier campo del hecho distinto (ítems,
         *     total, medio de pago, cliente, consecutivo, `creada_en_cliente` o
         *     estado) responde `rechazada` con motivo `venta_id_divergente` y los
         *     campos que difieren en `detalles.campos` — jamás un no-op silencioso.
         *     El dispositivo NO se compara: viaja en el lote, no en `datos`, así que
         *     un reintento del mismo id de venta desde OTRO dispositivo se reporta
         *     `duplicada` si el resto del payload coincide.
         *
         *     Doble verdad temporal (ADR-017/018): `creada_en_cliente` es el dato del
         *     ticket y se guarda tal cual; al comparar un reintento contra la venta ya
         *     aceptada se ignoran los microsegundos (la columna `timestamptz` no los
         *     conserva en el viaje de ida y vuelta), así que una diferencia sub-segundo
         *     NO convierte un reintento legítimo en `venta_id_divergente`. El orden de
         *     aplicación es el de recepción y el watermark del delta lo pone el reloj
         *     del servidor, nunca el del cliente.
         */
        post: operations["sincronizar_lote_api_v1_sync_lotes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** El negocio de la sesión actual */
        get: operations["mi_negocio_api_v1_tenants_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sonda de vida
         * @description Responde sin tocar ninguna dependencia externa.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sonda de vida (alias) */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sonda de disponibilidad */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Métricas Prometheus (requiere credencial propia) */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AjusteCreado
         * @description La respuesta del alta: lo mismo que la fila, más el nivel de alerta en
         *     que quedó el producto (lo deriva el servidor, que es la única autoridad
         *     del umbral — decisión 2).
         */
        AjusteCreado: {
            /** Aplicado Por */
            aplicado_por: string;
            /** Cantidad */
            cantidad?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Delta */
            delta: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Motivo */
            motivo: string;
            /** Nivel */
            nivel: string;
            /**
             * Producto Id
             * Format: uuid
             */
            producto_id: string;
            /** Stock Contado */
            stock_contado?: string | null;
            /** Stock Resultante */
            stock_resultante: string;
            /** Tipo */
            tipo: string;
        };
        /**
         * AjusteCrear
         * @description Un ajuste por conteo o una merma. ONLINE obligatorio (ADR-020): el
         *     delta se calcula contra el stock del servidor en el momento.
         *
         *     `id` es REQUERIDO (decisión 4): es la PK de `ajustes_inventario` y la
         *     única ancla que hace seguro el reintento de una merma, que es un delta
         *     relativo. El `motivo` es obligatorio: un ajuste sin justificación es un
         *     desfalco con buenos modales.
         */
        AjusteCrear: {
            /** Cantidad */
            cantidad?: number | string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Motivo */
            motivo: string;
            /**
             * Producto Id
             * Format: uuid
             */
            producto_id: string;
            /** Stock Contado */
            stock_contado?: number | string | null;
            /**
             * Tipo
             * @enum {string}
             */
            tipo: "ajuste" | "merma";
        };
        /** AjusteSalida */
        AjusteSalida: {
            /** Aplicado Por */
            aplicado_por: string;
            /** Cantidad */
            cantidad?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Delta */
            delta: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Motivo */
            motivo: string;
            /**
             * Producto Id
             * Format: uuid
             */
            producto_id: string;
            /** Stock Contado */
            stock_contado?: string | null;
            /** Stock Resultante */
            stock_resultante: string;
            /** Tipo */
            tipo: string;
        };
        /**
         * CompraCrear
         * @description Una compra a proveedor. `proveedor_nombre` es texto libre (ADR-020:
         *     la factura es un papel; no hay tabla de proveedores). El `id` del
         *     cliente se acepta como PK (ADR-017): reenviar la misma compra es un
         *     no-op. El total NO viaja: lo calcula el servidor (decisión 7).
         */
        CompraCrear: {
            /** Fecha */
            fecha?: string | null;
            /** Id */
            id?: string | null;
            /** Items */
            items: components["schemas"]["CompraItemEntrada"][];
            /** Observaciones */
            observaciones?: string | null;
            /** Proveedor Nombre */
            proveedor_nombre: string;
        };
        /** CompraDetalleSalida */
        CompraDetalleSalida: {
            /** Created At */
            created_at?: string | null;
            /**
             * Fecha
             * Format: date
             */
            fecha: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Items */
            items: components["schemas"]["CompraItemSalida"][];
            /** Observaciones */
            observaciones?: string | null;
            /** Proveedor Nombre */
            proveedor_nombre: string;
            /** Total Centavos */
            total_centavos: number;
        };
        /**
         * CompraItemEntrada
         * @description Una línea de factura. El costo es el de ESTA compra: al confirmarse
         *     actualiza `ultimo_costo` del producto (ADR-020).
         */
        CompraItemEntrada: {
            /** Cantidad */
            cantidad: number | string;
            /** Costo Unitario Centavos */
            costo_unitario_centavos: number;
            /**
             * Producto Id
             * Format: uuid
             */
            producto_id: string;
        };
        /** CompraItemSalida */
        CompraItemSalida: {
            /** Cantidad */
            cantidad: string;
            /** Costo Unitario Centavos */
            costo_unitario_centavos: number;
            /**
             * Producto Id
             * Format: uuid
             */
            producto_id: string;
        };
        /** CompraSalida */
        CompraSalida: {
            /** Created At */
            created_at?: string | null;
            /**
             * Fecha
             * Format: date
             */
            fecha: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Observaciones */
            observaciones?: string | null;
            /** Proveedor Nombre */
            proveedor_nombre: string;
            /** Total Centavos */
            total_centavos: number;
        };
        /**
         * DeltaSalida
         * @description El drenado de datos de referencia hacia el dispositivo (ADR-017).
         *
         *     `hasta` es la marca del SERVIDOR que el dispositivo guarda y devuelve
         *     como próximo `desde`: el watermark nunca lo pone el reloj del cliente.
         *     `eliminados` son tumbas: el dispositivo los quita de su IndexedDB.
         */
        DeltaSalida: {
            /** Eliminados */
            eliminados: string[];
            /**
             * Hasta
             * Format: date-time
             */
            hasta: string;
            /** Productos */
            productos: components["schemas"]["ProductoSalida"][];
        };
        /** DispositivoRegistrar */
        DispositivoRegistrar: {
            /** Id */
            id?: string | null;
            /** Nombre */
            nombre: string;
        };
        /** DispositivoSalida */
        DispositivoSalida: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nombre */
            nombre: string;
            /** Ultima Secuencia */
            ultima_secuencia: number;
            /** Ultima Sync */
            ultima_sync?: string | null;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /**
             * Code
             * @default ERROR
             */
            code: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            } | null;
            /** Message */
            message: string;
            /**
             * Success
             * @default false
             */
            success: boolean;
        };
        /**
         * EstadoTenant
         * @description Estados de un negocio. Sin tildes ni eñes: viajan en JSON y en URLs.
         * @enum {string}
         */
        EstadoTenant: "activo" | "suspendido" | "eliminado";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoteSync */
        LoteSync: {
            /**
             * Dispositivo Id
             * Format: uuid
             */
            dispositivo_id: string;
            /** Operaciones */
            operaciones: components["schemas"]["OperacionSync"][];
        };
        /**
         * OperacionSync
         * @description Una operación de la cola del dispositivo.
         *
         *     `tipo` es texto libre acotado, no Literal: un tipo desconocido (cliente y
         *     servidor de versiones distintas) es `rechazada` por operación, no un 422
         *     del lote entero (decisión 6). `datos` es REQUERIDO (cierre de D-14) y
         *     viaja como dict: lo valida el servicio contra
         *     `VentaCrearSync`/`VentaAnularSync` por la misma razón.
         */
        OperacionSync: {
            /** Datos */
            datos: {
                [key: string]: unknown;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Secuencia */
            secuencia: number;
            /** Tipo */
            tipo: string;
        };
        /** PagedList[AjusteSalida] */
        PagedList_AjusteSalida_: {
            /** Items */
            items: components["schemas"]["AjusteSalida"][];
            /** Limit */
            limit: number;
            /** Skip */
            skip: number;
            /** Total */
            total: number;
        };
        /** PagedList[CompraSalida] */
        PagedList_CompraSalida_: {
            /** Items */
            items: components["schemas"]["CompraSalida"][];
            /** Limit */
            limit: number;
            /** Skip */
            skip: number;
            /** Total */
            total: number;
        };
        /** PagedList[ProductoSalida] */
        PagedList_ProductoSalida_: {
            /** Items */
            items: components["schemas"]["ProductoSalida"][];
            /** Limit */
            limit: number;
            /** Skip */
            skip: number;
            /** Total */
            total: number;
        };
        /** PagedList[StockSalida] */
        PagedList_StockSalida_: {
            /** Items */
            items: components["schemas"]["StockSalida"][];
            /** Limit */
            limit: number;
            /** Skip */
            skip: number;
            /** Total */
            total: number;
        };
        /** PagedList[TenantSalida] */
        PagedList_TenantSalida_: {
            /** Items */
            items: components["schemas"]["TenantSalida"][];
            /** Limit */
            limit: number;
            /** Skip */
            skip: number;
            /** Total */
            total: number;
        };
        /**
         * ProductoActualizar
         * @description Todo opcional: es un PATCH. `None` significa "no lo toques" (misma
         *     convención que `TenantActualizar`).
         *
         *     No lleva `stock_actual` ni `ultimo_costo`: el stock lo mueven los
         *     movimientos de inventario y el costo las compras (ADR-020). Un endpoint
         *     que dejara editar el contador a mano rompería la invariante del libro.
         */
        ProductoActualizar: {
            /** Categoria */
            categoria?: string | null;
            /** Codigo Barras */
            codigo_barras?: string | null;
            /** Iva Pct */
            iva_pct?: number | string | null;
            /** Nombre */
            nombre?: string | null;
            /** Padre Id */
            padre_id?: string | null;
            /** Precio Venta */
            precio_venta?: number | null;
            /** Stock Minimo */
            stock_minimo?: number | string | null;
            /** Unidad Medida */
            unidad_medida?: string | null;
        };
        /** ProductoCrear */
        ProductoCrear: {
            /** Categoria */
            categoria?: string | null;
            /** Codigo Barras */
            codigo_barras?: string | null;
            /** Id */
            id?: string | null;
            /**
             * Iva Pct
             * @default 0
             */
            iva_pct: number | string;
            /** Nombre */
            nombre: string;
            /** Padre Id */
            padre_id?: string | null;
            /** Precio Venta */
            precio_venta: number;
            /**
             * Stock Minimo
             * @default 0
             */
            stock_minimo: number | string;
            /**
             * Unidad Medida
             * @default unidad
             */
            unidad_medida: string;
        };
        /** ProductoSalida */
        ProductoSalida: {
            /** Categoria */
            categoria?: string | null;
            /** Codigo Barras */
            codigo_barras?: string | null;
            /** Created At */
            created_at?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Iva Pct */
            iva_pct: string;
            /** Nombre */
            nombre: string;
            /** Padre Id */
            padre_id?: string | null;
            /** Precio Venta */
            precio_venta: number;
            /** Stock Actual */
            stock_actual: string;
            /** Stock Minimo */
            stock_minimo: string;
            /** Ultimo Costo */
            ultimo_costo?: number | null;
            /** Unidad Medida */
            unidad_medida: string;
        };
        /**
         * RespuestaLote
         * @description Un resultado por operación, en el MISMO orden del lote.
         */
        RespuestaLote: {
            /** Resultados */
            resultados: components["schemas"]["ResultadoOperacion"][];
        };
        /**
         * ResultadoOperacion
         * @description El desenlace de UNA operación del lote (ADR-017):
         *
         *     - `aceptada`: se aplicó (venta registrada/anulada, stock movido, evento
         *       encolado — todo en la transacción del lote).
         *     - `duplicada`: ya estaba aplicada exactamente igual; no-op sin evento.
         *     - `rechazada`: bien formada pero negada por el dominio; `motivo` es el
         *       `code` estable y `detalles` el contexto (campos divergentes, etc.).
         */
        ResultadoOperacion: {
            /** Detalles */
            detalles?: {
                [key: string]: unknown;
            } | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Motivo */
            motivo?: string | null;
            /**
             * Resultado
             * @enum {string}
             */
            resultado: "aceptada" | "duplicada" | "rechazada";
            /** Tipo */
            tipo: string;
        };
        /**
         * StockSalida
         * @description El stock de un producto con su nivel derivado (agotado/crítico/bajo/ok).
         *
         *     El nivel lo calcula el servidor con la misma función que dispara las
         *     alertas: una sola definición del umbral, ninguna reimplementación en el
         *     frontend. El stock negativo es un dato legítimo (ADR-020) y viaja tal
         *     cual con nivel `agotado`.
         */
        StockSalida: {
            /** Nivel */
            nivel: string;
            /** Nombre */
            nombre: string;
            /**
             * Producto Id
             * Format: uuid
             */
            producto_id: string;
            /** Stock Actual */
            stock_actual: string;
            /** Stock Minimo */
            stock_minimo: string;
        };
        /**
         * TenantActualizar
         * @description Todo opcional: es un PATCH. `None` significa "no lo toques".
         */
        TenantActualizar: {
            estado?: components["schemas"]["EstadoTenant"] | null;
            /** Nombre */
            nombre?: string | null;
        };
        /** TenantCrear */
        TenantCrear: {
            /** Nombre */
            nombre: string;
        };
        /** TenantSalida */
        TenantSalida: {
            /** Created At */
            created_at?: string | null;
            estado: components["schemas"]["EstadoTenant"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kc Org Id */
            kc_org_id?: string | null;
            /** Nombre */
            nombre: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listar_compras_api_v1_compras_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedList_CompraSalida_"];
                };
            };
            /** @description Falta el token o no es válido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Falta el permiso o el negocio está suspendido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request malformado (validación de estructura o de dominio) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    registrar_compra_api_v1_compras_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompraCrear"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompraDetalleSalida"];
                };
            };
            /** @description Falta el token o no es válido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Falta el permiso o el negocio está suspendido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description El id de la compra ya existe (en este u otro negocio) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request malformado (validación de estructura o de dominio) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ver_compra_api_v1_compras__compra_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                compra_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompraDetalleSalida"];
                };
            };
            /** @description Falta el token o no es válido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Falta el permiso o el negocio está suspendido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description La compra no existe */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request malformado (validación de estructura o de dominio) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    registrar_dispositivo_api_v1_dispositivos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DispositivoRegistrar"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DispositivoSalida"];
                };
            };
            /** @description Falta el token o no es válido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Falta el permiso o el negocio está suspendido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description El id del dispositivo ya existe (en este u otro negocio) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request malformado (validación de estructura) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listar_ajustes_api_v1_inventario_ajustes_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedList_AjusteSalida_"];
                };
            };
            /** @description Falta el token o no es válido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Falta el permiso o el negocio está suspendido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request malformado (validación de estructura o de dominio) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    registrar_ajuste_api_v1_inventario_ajustes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AjusteCrear"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AjusteCreado"];
                };
            };
            /** @description Falta el token o no es válido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Falta el permiso o el negocio está suspendido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description El id del ajuste ya existe con datos distintos */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request malformado (validación de estructura o de dominio) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    estado_de_stock_api_v1_inventario_stock_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
                /** @description Solo productos agotados o por debajo del mínimo */
                solo_alertas?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedList_StockSalida_"];
                };
            };
            /** @description Falta el token o no es válido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Falta el permiso o el negocio está suspendido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request malformado (validación de estructura o de dominio) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listar_tenants_api_v1_platform_tenants_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
                incluir_eliminados?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedList_TenantSalida_"];
                };
            };
            /** @description Falta el token o no es válido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description El token no trae el permiso platform:admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_tenant_api_v1_platform_tenants_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantCrear"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantSalida"];
                };
            };
            /** @description Falta el token o no es válido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description El token no trae el permiso platform:admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Keycloak no pudo crear la organización */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ver_tenant_api_v1_platform_tenants__tenant_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantSalida"];
                };
            };
            /** @description Falta el token o no es válido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description El token no trae el permiso platform:admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No existe */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    eliminar_tenant_api_v1_platform_tenants__tenant_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Falta el token o no es válido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description El token no trae el permiso platform:admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No existe */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    actualizar_tenant_api_v1_platform_tenants__tenant_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantActualizar"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantSalida"];
                };
            };
            /** @description Falta el token o no es válido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description El token no trae el permiso platform:admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No existe */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_productos_api_v1_productos_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
                /** @description Texto a buscar en el nombre */
                q?: string | null;
                categoria?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedList_ProductoSalida_"];
                };
            };
            /** @description Falta el token o no es válido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Falta el permiso o el negocio está suspendido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_producto_api_v1_productos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductoCrear"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductoSalida"];
                };
            };
            /** @description Falta el token o no es válido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Falta el permiso o el negocio está suspendido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description El producto no existe */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description EAN duplicado o id ya usado */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    buscar_por_codigo_api_v1_productos_por_codigo__codigo__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                codigo: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductoSalida"];
                };
            };
            /** @description Falta el token o no es válido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Falta el permiso o el negocio está suspendido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description El producto no existe */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ver_producto_api_v1_productos__producto_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                producto_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductoSalida"];
                };
            };
            /** @description Falta el token o no es válido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Falta el permiso o el negocio está suspendido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description El producto no existe */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    eliminar_producto_api_v1_productos__producto_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                producto_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Falta el token o no es válido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Falta el permiso o el negocio está suspendido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description El producto no existe */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    actualizar_producto_api_v1_productos__producto_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                producto_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductoActualizar"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductoSalida"];
                };
            };
            /** @description Falta el token o no es válido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Falta el permiso o el negocio está suspendido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description El producto no existe */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description EAN duplicado */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delta_de_sync_api_v1_sync_delta_get: {
        parameters: {
            query: {
                /** @description Watermark devuelto como `hasta` por el delta anterior (o una fecha inicial) */
                desde: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeltaSalida"];
                };
            };
            /** @description Falta el token o no es válido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Falta el permiso o el negocio está suspendido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request malformado (validación de estructura) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    sincronizar_lote_api_v1_sync_lotes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoteSync"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaLote"];
                };
            };
            /** @description Falta el token o no es válido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Falta el permiso o el negocio está suspendido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request malformado (validación de estructura) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    mi_negocio_api_v1_tenants_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantSalida"];
                };
            };
            /** @description El negocio está suspendido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description El negocio ya no existe */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
